Import('RTT_ROOT')
Import('rtconfig')
from building import *

src	= Glob('*.c')

cwd = GetCurrentDir()

CPPPATH = [cwd]

group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
