from building import *

cwd = GetCurrentDir()
src	= Glob('*.c') + Glob('*.S')

CPPPATH = [cwd]
CPPDEFINES = ['CHIP_MX6UL']

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)

Return('group')
